version: "3.1"

services:
  server:
    build: server/
    depends_on:
      - db
    ports:
      - "4200:4200"
  
  db:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
